### ISSUE TITLE
Release 0.0.6 to RubyGems (to include 'GET' patch from PR #4)

### ISSUE THREAD

**Issue by Whelton** [payfort/start-ruby#8]
Hi, 
could version 0.0.6 please be pushed to ruby gems so as to include the 'GET' patch from PR #4.

Using `start-ruby` in a gem and got caught when attempting to retrieving/validating tokens :) 

Thank you,
James

Also P.S. I don't know this isn't the place to comment on this, but would be nice to add the 'Retrieve Token' to the [API documentation](https://docs.start.payfort.com/references/api/?shell#tokens) for when validating tokens server side before creating a customer or a card, I know it's implied as its a RESTful API, but I had to do a double take. Thank you

**Comment by alovak** [comment]
@Whelton done!

thanks for your comment ;)

**Comment by Whelton** [comment]
Awesome, thank you for incredible turn around :) 
Have a good one!
